// LOCAL
### GET home
GET http://localhost:3001

### GET all cars
GET http://localhost:3001/cars

### GET specific car
GET http://localhost:3001/cars/65b44b7e09db0c26eaf3582a

### Add car (POST)
POST http://localhost:3001/cars
Content-Type: application/json

{ 
  "year": "1972",
  "make": "Ford",
  "model": "Capri",
  "color": "Blue",
  "engine": "2600 cc",
  "transmission": "Manual",
  "gears": "4",
  "shifter": "Console"
}

### Update car (PUT)
PUT http://localhost:3001/cars/65b4491409db0c26eaf35826
Content-Type: application/json

{ 
  "_id": "65b4491409db0c26eaf35826",
  "year": "1969",
  "make": "Ford",
  "model": "Mustang Mach I",
  "color": "Red",
  "engine": "351 ci",
  "transmission": "Manual",
  "gears": "4",
  "shifter": "Console"
}

### Delete car
DELETE http://localhost:3001/cars/<id>

// PRODUCTION
### GET home
GET https://cse341bh-project2.onrender.com

### GET all cars
GET https://cse341bh-project2.onrender.com/cars

### GET specific car
GET https://cse341bh-project2.onrender.com/cars/659f0f04ea5421b2800b9a1d

### Add car (POST car)
POST https://cse341bh-project2.onrender.com/cars
Content-Type: application/json

{ 
  "year": "1971",
  "make": "Chevrolet",
  "model": "Vega",
  "color": "Orange",
  "engine": "2300 cc",
  "transmission": "Manual",
  "gears": "4",
  "shifter": "Floor"
}

### Change car information (PUT)
PUT https://cse341bh-project2.onrender.com/cars/659f0f04ea5421b2800b9a1d
Content-Type: application/json

{ 
    "_id": "65b447ec09db0c26eaf35824",
    "year": "1971",
    "make": "Dodge",
    "model": "Charger 500",
    "color": "White/Tan",
    "engine": "383 ci",
    "transmission": "Automatic",
    "gears": "3",
    "shifter": "Console"
}

### Remove a car (DELETE)
DELETE https://cse341bh-project2.onrender.com/cars/<id>
