// LOCAL
### GET home
GET http://localhost:3001

### GET all dogs
GET http://localhost:3001/dogs

### GET specific dog
GET http://localhost:3001/dogs/<id>

### Add dog (POST)
POST http://localhost:3001/dogs
Content-Type: application/json

{ 
  "name": "Griz",
  "breed": "Brazilian Mastiff",
  "gender": "Male",
  "color": "Browndsfjadlfjsa;jdfa"
}

### Update dog (PUT)
PUT http://localhost:3001/dogs/<id>
Content-Type: application/json

{ 
  "name": "Griz",
  "breed": "Brazilian Mastiff",
  "gender": "Male",
  "color": "Brown"
}

### Delete dog
DELETE http://localhost:3001/dogs/<id>



// PRODUCTION
### GET home
GET https://cse341bh-project2.onrender.com

### GET all dogs
GET https://cse341bh-project2.onrender.com/dogs

### GET specific dog
GET https://cse341bh-project2.onrender.com/dogs/<id>

### Add dog (POST dog)
POST https://cse341bh-project2.onrender.com/dogs
Content-Type: application/json

{ 
  "name": "Griz",
  "breed": "Brazilian Mastiff",
  "gender": "Male",
  "color": "Brown"
}

### Change dog information (PUT)
PUT https://cse341bh-project2.onrender.com/dogs/<id>
Content-Type: application/json

{ 
  "name": "Griz",
  "breed": "Brazilian Mastiff",
  "gender": "Male",
  "color": "Brown"
}

### Remove a dog (DELETE)
DELETE https://cse341bh-project2.onrender.com/dogs/<id>
